### ISSUE TITLE
В описании сборки BS неверно указан звукоизлучатель HC0903A

### ISSUE THREAD

**Issue by KrepakVitaly** [alexandervolikov/sportiduino#103]
В описании сборки Base Station неверно указан звукоизлучатель HC0903A -- аналогом TR1205Y является HCM1203A, который сейчас проще найти в терраэлектронике или чипидипе.

Различие в шаге выводов и направлении излучателя, HC0903A имеет меньший шаг, чем монтажные отверстия, и направлен вбок, что мешает качественно залить блок силиконовым компаундом.

**Comment by sembruk** [comment]
Спасибо! Исправлено.
