### ISSUE TITLE
Как увеличить расстояние от приемника до метки RFID?

### ISSUE THREAD

**Issue by kentforth** [alexandervolikov/sportiduino#107]
У меня стоит задача трекать RFID метки на расстоянии примерно 3-6 метров. Сохранять время метки.
Метки буду брать с алиэкспресс, метки типа таких
https://aliexpress.ru/item/1005001403997268.html?spm=a2g2w.productlist.0.0.752541f0PbMJes

Какие есть варианты увеличения расстояния трека RFID метки?

**Comment by myadzel** [comment]
Пассивные RFID-метки не могут работать на таких расстояниях, их предел это несколько сантиметров. Есть активные метки, но это другая история.

**Comment by sembruk** [comment]
Для меток по стандарту ISO/IEC 14443 радиус действия ограничен на физическом уровне. Чего-то можно добиться только увеличением антены считывателя.
https://datasheet.datasheetarchive.com/originals/library/Datasheets-SW16/DSASW00306307.pdf
![ra1_fig02](https://user-images.githubusercontent.com/16308981/138337654-37eeee0f-6146-45c6-99fe-f5b67f8c85a7.jpg)
![photo5373259028420997983](https://user-images.githubusercontent.com/16308981/138337545-f5fa3022-7310-4a6a-abba-408429a9dc3b.jpg)
