### ISSUE TITLE
Баг с записью чипов

### ISSUE THREAD

**Issue by alexandervolikov** [alexandervolikov/sportiduino#13]
С некоторым шансом при плохих условиях прикладывания чипа станция пишет отметку не в последнюю пустую страницу а в какую-то промежуточную.
Вероятно, при считывании с какой-то пустой страницы, на станцию приходит, что она не пустая.
Из-за этого явления возникают критические ошибки с перезаписью уже существующих данных на страницы.
Возможно, при очистке нужно писать в страницы не нули, а какую-то контрольную информацию.
А пока прошивками 0.42.x пользоваться нельзя.

**Comment by mforis** [comment]
Скиньте пожалуйста, самую стабильную на данный момент прошивку.

**Comment by alexandervolikov** [comment]
Точно стабильная - это 0.37. На ней проводились соревнования, и всё было хорошо. Но она рассчитана на 46 отметок
https://github.com/alexandervolikov/sportiduino/tree/fbe66d3bbb6a0b0fddf518feaf086d0d8c350f17
Если важно именно 92 отметки, то, вероятно, последняя устойчивая версия - 0.41. До введения бинарного поиска.
https://github.com/alexandervolikov/sportiduino/tree/7e51d193c366d96c4dc2d69648cfd7573fe4ffbb

**Comment by mforis** [comment]
Спасибо, пока достаточно 46 отметок. Со дня-на-день придут МК, до соберу и буду прошивать. Уже не терпится провести полевые испытания))) фотки:
![img_20171114_205720](https://user-images.githubusercontent.com/32615135/32796232-33d25cca-c97f-11e7-907f-8c13f7c054ba.jpg)
![img_20171114_205815_hdr](https://user-images.githubusercontent.com/32615135/32796233-340867b6-c97f-11e7-9039-7a791b5c4720.jpg)

**Comment by alexandervolikov** [comment]
Отлично! Если что, пишите. А баг я постараюсь в скором времени ликвидировать.

**Comment by alexandervolikov** [comment]
Баг исправил. Проблема возникла из-за того, что функция поиска последней страницы в случае неудачного поиска (если чип был приложен плохо) не вызывала выход из функции записи чипов, в результате чего станция могла записать метку в страницу, которую считала у предыдущего чипа.
Сейчас исправлено. Также решил отказаться от 92 меток и записывать на Mifare Classic только 46 меток, по числу страниц, чтобы повысить надежность записи.
