### ISSUE TITLE
Интеграция со SportOrg

### ISSUE THREAD

**Issue by daxartio** [alexandervolikov/sportiduino#16]
Есть предложение интегрировать систему в программу SportOrg github.com/sportorg/pysport

**Comment by alexandervolikov** [comment]
Интересно! Написал Вам на почту.

**Comment by mforis** [comment]
А будет ли программа поддерживать Mifare Classic?

**Comment by alexandervolikov** [comment]
Это задается на уровне прошивки станции сопряжения, работа программы от типа чипа не зависит. Прошивку, поддерживающую Mifare, я позже тоже выложу.
