### ISSUE TITLE
Проблемы базами

### ISSUE THREAD

**Issue by mforis** [alexandervolikov/sportiduino#19]
Такая проблема, был совершен акт вандализма и корпус одной из баз поврежден, плата с включенным питание пролежала в снегу около 30 минут. После ремонта, база перестала читать синие чипы и с большой задержкой читает белые. Такая-же проблема была в одной из баз с самого начала. Возможно ли как-то побороть проблему?

**Comment by alexandervolikov** [comment]
Здравствуйте. Не сталкивался с такой проблемой, однозначно сказать, в чем неисправность не могу. Вполне возможно, повредилась какая-нибудь микросхема, но искать конкретную причину может быть весьма времязатратно.
Между синими чипами и белыми карточками разница в площади антены у чипа. Для карточек нужна меньшая плотность передаваемой станцией энергии. То есть, в Вашем случае у станции снизилась мощность по какой-то причине. Может помочь перепаять индуктивности на более мощные в модуле RC522, если Вы этого ещё не делали. Существенно повышает дальность работы станции. На фото обведены красным квадратом:
https://raw.githubusercontent.com/alexandervolikov/sportiduino/master/Images/s12_1.JPG
например, на такие:
https://www.chipdip.ru/product/lqh32mn2r2k
