### ISSUE TITLE
Сделать более легкособираемый вариант станции

### ISSUE THREAD

**Issue by alexandervolikov** [alexandervolikov/sportiduino#2]
На материнской плате собирается навесным монтажом из блоков: Arduino pro mini, Ds3231, RC522.
Большая герметичная коробка, например, G203CMF

**Comment by burunduk** [comment]
Про вариант: У китайцев популярна плата часов с батарейкой CR2032, и епром 32к и штырями.
это не увеличит автономность?

**Comment by alexandervolikov** [comment]
Да, причем в плате с часами и батарейкой есть уже епром на 4к. Её и буду использовать для данного варианта. Платы для сборки из модулей уже приехали, скоро соберу, выложу что получилось.

**Comment by fimich1** [comment]
Не могли бы выложить макет платы дляч этого варианта, какой результат?

**Comment by alexandervolikov** [comment]
Поэкспериментировав, решил отказаться от этой идеи. С учетом необходимых доработок готовых плат (удаление лишних диодов и пр.), большего объема пайки (каждую ножку платы), проще и быстрее использоваться отдельные микросхемы как это реализовано сейчас в основном варианте.
