### ISSUE TITLE
Верия прошивки

### ISSUE THREAD

**Issue by sembruk** [alexandervolikov/sportiduino#22]
https://github.com/alexandervolikov/sportiduino/blob/628fbad52e6b0545ea1de903ada806bc26f75a08/Master%20station/MasterStation/MasterStation.ino#L5

Точно версия 101? Или должна быть 110?

Ещё была бы полезна команда запроса версии прошивки мастер-станции.
Это позволит в будущем ПО работать со старыми станциями, если протокол обмена будет дополняться или даже изменяться.

**Comment by alexandervolikov** [comment]
Да, точно. 
Систему версий думаю вести с использованием чисел до 99.
То есть, нынешний вариант, можно обозначить как 1.01.0
А третье число- для обозначения мелких изменений, не отражаемых на работе других компонентов системы.

Да, команду добавил, 0x46
ответ 0x66 и номер
