### ISSUE TITLE
Проблема с NTAG213

### ISSUE THREAD

**Issue by mforis** [alexandervolikov/sportiduino#24]
Купил я себе чипы NTAG213 в виде наклеек, прошил базу чтения на самую новую прошивку, скачал самый новый софт, но при попытке инициализировать чип, база подает три последовательных сигнала, пробовал несколько разных наклеек, но результат тщетен. В чем может быть проблема?

**Comment by sembruk** [comment]
Можно попробовать с прошивкой v1.1 и соответсвующим этой версии софтом.

**Comment by alexandervolikov** [comment]
Последние прошивки только что ещё раз проверил. Всё работает.
Тут, вероятно, присутствуют аппаратные проблемы. Три сигнала станция подает, когда передача сигнала некорректная, например, если связь между чипом и станцией нестабильная.  Ntag213 отличается от Mifare1K тем, что требуют большую энергию при передаче, поэтому целесообразно в модуле RC522 перепаять индуктивность на более мощную. Хотя в виде наклеек должны бы работать и без перепайки.
А что пишет в лог при поднесении чипа и нажатии кнопки "Read raw"?
