### ISSUE TITLE
Поднять скорость обмена по UART до 115200

### ISSUE THREAD

**Issue by sembruk** [alexandervolikov/sportiduino#26]
Проверил. Работает.

**Comment by alexandervolikov** [comment]
Тоже пробовал. У меня почему-то не работает. Но да это вроде и не особо принципиально, скорость передачи ограничена скоростью чтения чипа - порядка 20 мс на чтение одной страницы чипа, то есть, порядка 2000 бауд.

**Comment by sembruk** [comment]
Да, в таком случае смысла поднимать скорость пока нет.
