### ISSUE TITLE
Усилить громкость сигнала

### ISSUE THREAD

**Issue by alexandervolikov** [alexandervolikov/sportiduino#31]
Завести пищалку через транзистор.

**Comment by mforis** [comment]
Как вариант, чтобы МК подавал сигнал на открытие транзистора, а саму пищалка запитать от батареек через транзистор.

**Comment by alexandervolikov** [comment]
Да, именно это я и имел в виду

**Comment by alexandervolikov** [comment]
Добавил транзистор в схему. Стало погромче. 
Загрузил новый гербер. Уже готовые можно проапгрейдить с помощью проводов примерно так. Нужно перерезать две дорожки ведущие к пищалке. подпаять транзистор.
![img_20180411_071440](https://user-images.githubusercontent.com/24255199/38603925-a80690ea-3d77-11e8-99b0-e684c578d152.jpg)

**Comment by mforis** [comment]
Да, надо попробовать, у меня как раз много биполярных транзисторов, но лень разбирать 20 баз...
