### ISSUE TITLE
Нюансы в прошивке 1.3.4

### ISSUE THREAD

**Issue by mforis** [alexandervolikov/sportiduino#33]
Доброго времени суток! Обновил я прошивки в своих базах, но нашел некоторые недороботки(по моему мнению):
1. Станция проверки не выполняет свою функцию. Например, я взял чип, чтобы "усыпить" базы, через компьютер его не очищаю, очищаю с помощью базы очистки - всё прошло успешно, прикладываю к базе проверки - успешно, выдаю участнику и опа - чип не отмечается на старте.
2. К примеру, я очистил чип базой очистки, решил проверить работоспособность базовых станций, прикладываю чип к базе очистке - очистка не происходит!
3. Зачем при входе в сон сбрасывать настройки, ведь неудобно, перед каждыми соревнованиями выставлять, что-бы старт был обязательным.

**Comment by alexandervolikov** [comment]
1. Да, с судейскими чипами станция проверки не работает корректно. В следующей прошивке исправлю.
2. База очистки сейчас не может очищать подряд два чипа с одним и тем же номером (сделал, чтобы очистка случайно не шла по кругу). В следующей прошивке учту, а пока нужно чередовать чипы с разными номерами.
3. Это я сделал прежде всего для других настроек, чтобы случайно станции не оказались неработоспособными. Подумаю как можно сделать это более удобным. Пока можете в строчке 820 для MifareBaseStation:  for (uint8_t i = 0;i<4;i++){
4 заменить на 3, чтобы настройки не сбивались

**Comment by mforis** [comment]
Хорошо, с этим понятно. Но вот заметил ещё одну проблему, одна из баз, среди ночи начала издавать периодические длинные сигнала, до тех пор, пока не отключил питание. Может ли это быть потому, что я временно заменил стабилизатора на AMS1117?

**Comment by alexandervolikov** [comment]
Обновил прошивки. в 1.3.5. постарался исправить всё это. Но пока не тестировал.

На счёт издавания длинных сигналов - это станция зависает и перезагружается по кругу. Да, возможно, какие-то проблемы с питанием.

**Comment by mforis** [comment]
Александр, еще такой вопрос, а можно ли подпаять электролит к часам? или только керамика?

**Comment by alexandervolikov** [comment]
Думаю, что можно. Удобно smd конденсатор впаивать, там по сути между соседними ножками, вот как я впаивал
![img_20180619_214755](https://user-images.githubusercontent.com/24255199/41618111-f03808c0-740a-11e8-88ac-2fa63a8e9f2a.jpg)

**Comment by mforis** [comment]
Протестировал версию 1.3.5. 
1. Настройки не сбивается.
2. Мастер-чипы по прежнему работают некорректно.
3. С базой очистки всё идеально!
4. При прикладывании чипа к базе проверки она издает три сигнала и так на все чипы, в т. ч. мастер-чипы, только- что очищенные и (или) инициализированные.

**Comment by alexandervolikov** [comment]
Возможно, это из-за того, что время на станции проверки сбито. То есть, если разница между временем инициализации (очистки) и текущим превышает месяц, станция проверки также издает сигнал ошибки.

**Comment by mforis** [comment]
Да, нет, обновлял время несколько раз.

**Comment by alexandervolikov** [comment]
Да, не учёл один ньюанс для Mifare карт. Сейчас поправил, протестировал, вроде работает корректно.

**Comment by mforis** [comment]
Ведь можно же обновить прошивку только в базе проверки, чтобы все не прошивать?

**Comment by alexandervolikov** [comment]
Да, конечно. Если использовать станции как базовые, ничего не поменялось с 1.3.0.

**Comment by mforis** [comment]
Александр, не могли бы вы скинуть мне файл settings.csv? А то поменял setst на 44, а настройки всё равно сбиваются...

**Comment by mforis** [comment]
Хотя... Оказалось, что проблема только в одной базе, наверное не обновил прошивку

**Comment by mforis** [comment]
Блин, нет, всё-же скиньте

**Comment by alexandervolikov** [comment]
Вот. Только 44 для Mifare тоже что и 12.
[settings.zip](https://github.com/alexandervolikov/sportiduino/files/2129038/settings.zip)

**Comment by mforis** [comment]
К сожалению, не помогло. Может проблема в прошивке?

**Comment by alexandervolikov** [comment]
Да, проверил, действительно, не работает. Попробую разобраться в чем дело.
А пока просто используйте для базовых станций пошивку 1.3.0, а для станции очистки и проверки 1.3.5.

**Comment by alexandervolikov** [comment]
Нашёл источник ошибки. Исправил в 1.3.6. Протестировал, работает, настройки не сбрасываются.
Также для Mifare не работает проверка времени инициализации чипа в режиме базовой станции.
