### ISSUE TITLE
Соревнования проведенные на Sportiduino

### ISSUE THREAD

**Issue by mforis** [alexandervolikov/sportiduino#34]
Сегодня провел соревнования с заданной дистанцией, всё отработало без проблем, если не учесть, что какие-то нелюди украли: призму, стойку и базу. Участвовало 48 человек. 
![image](https://user-images.githubusercontent.com/32615135/41937013-ce0c75aa-7997-11e8-8a18-58da354418c5.png)

**Comment by alexandervolikov** [comment]
Поздравляю!
А против вандалов или кражи тут уж едва что сделаешь, остается радоваться, что это была не арендованная sportIdent станция.
