### ISSUE TITLE
Разработка корпуса для базовой станции

### ISSUE THREAD

**Issue by mforis** [alexandervolikov/sportiduino#38]
![image](https://user-images.githubusercontent.com/32615135/43154512-3eec91ba-8f7d-11e8-82fb-813a2a1af680.png)

**Comment by alexandervolikov** [comment]
А какое крепление крышки к коробке? По-хорошему, нужно сделать желоб для резиновой прокладки, чтобы обеспечить герметичность без использования компаунда.

**Comment by mforis** [comment]
Да, это всё будет. Я продумываю, как лучше это всё сделать.
