### ISSUE TITLE
Программа для обработки результатов

### ISSUE THREAD

**Issue by vasyaabr** [alexandervolikov/sportiduino#40]
Просто как идея: вы можете на заморачиваться на отдельную программу для обработки результатов, всё таки это довольно сложно - предусмотреть много вариантов соревнований, а использовать, например, MeOS (http://www.melin.nu/meos/en/). 

Она очень функциональная и имеет поддержку считывания произвольных систем электронной отметки - надо будет только написать прослойку, которая передаст на нужный сокет пакет отметок с чипа (там есть документация и примеры).

Так же в своё время поступили SFR sytem - тоже написали свой драйвер для MeOS.

**Comment by alexandervolikov** [comment]
Сейчас так и сделано с программой SportOrg (http://sportorg.o-ural.ru/). Написан модуль, который там подключили, и теперь можно с ней работать. 
Конечно, я только за, если кто-то напишет драйвер для MeOS, но сам я за это не возьмусь.

**Comment by mforis** [comment]
Я думаю, стоит вложить усилия в программу для андроид, так как для компьютера программ вполне достаточно.

**Comment by alexandervolikov** [comment]
Да, согласен. К тому же есть станция сопряжения с Bluetooth модулем.

**Comment by se-ti** [comment]
> Я думаю, стоит вложить усилия в программу для андроид, так как для компьютера программ вполне достаточно.

@mforis, если тема с андроидом еще интересна,  посмотрите https://sfrreader.github.io/ 
Если заинтересует -- можно обсудить поддержку Sportiduino

**Comment by mforis** [comment]
@se-ti , да, стоит с ними обсудить добавление поддержки Sportiduino

**Comment by se-ti** [comment]
Не "с ними", а со мной :)

**Comment by mforis** [comment]
@se-ti , хорошо, нужно о каких-то условиях договориться?

**Comment by se-ti** [comment]
@mforis, ответил в почте

**Comment by sembruk** [comment]
В MeOS теперь работает через эмуляцию SPORTident.
[Android приложение](https://github.com/sportiduino/sportiduinoapp) есть.
