### ISSUE TITLE
Вопрос по прошивке для Ntag чипов.

### ISSUE THREAD

**Issue by halny123** [alexandervolikov/sportiduino#49]
Недавно была доработана прошивка для Mifare чипов. СПАСИБО Антону.
Получилось очень интересно.
Можно ли ожидать такое для Ntag чипов ?
Сейчас, если я правильно понял, функционал у различных прошивок разный ?

**Comment by mars2860** [comment]
От меня скорее всего не стоит этого ожидать. Также новая прошивка для Mifare работает только с новой версией схемы. Документацию по всему этому делу ещё не поправил, к сожалению

**Comment by mars2860** [comment]
начиная с версии 2.6.0 теперь одна прошивка одновременно работает как с mifare так и ntag, прошивку можно поставить на платы версии 1
