### ISSUE TITLE
Чипы на запястье или на палец

### ISSUE THREAD

**Issue by alexandervolikov** [alexandervolikov/sportiduino#5]
Заказ и тестирование.

**Comment by alexandervolikov** [comment]
Возможность есть. Заказал и протестировал несколько образцов.

Чипы в виде браслета (но можно и на палец крепить резинкой) стоят из Китая при заказе партии в 1000 штук - по 20 рублей, 500 штук - 30 рублей. Но сюда ещё нужно включить стоимость доставки, возможные проблемы с растаможкой. 
Искать на алибабе по "rfid wristband". Нужный чип - F1108 Fudan. Это полный Китайский дешевый аналог Mifare Classik 1K. Под дешевыми чипами подразумеваются именно они.

В России при беглом поиске и переписке с поставщиками нашёл чипы по цене от 70 рублей за чип в виде браслета с текстильным ремешком.

**Comment by mforis** [comment]
А подходят ли чипы которые идут в комплекте с rfid считывателем (белые карточки и синие чипы) к этому проекту?

**Comment by alexandervolikov** [comment]
Да, подходят. Там FM1108, китайский аналог Mifare Classik 1K
