### ISSUE TITLE
Проблемы с записью чипов базовой станцией

### ISSUE THREAD

**Issue by SergeyZaboev** [alexandervolikov/sportiduino#51]
Здравствуйте, собрал мастер-станцию и станции отметки последней версии, прошил их прошивками для чипов ntag. Вывел станцию отметки из сна, приложив мастер-чип для стартовой станции, затем сделал чип для коррекции часов и приложил его до сигнала станции, аналогично сделал для станций отметки. Другому чипу в SportIduinoPQ присвоил номер 1. Затем делал отметку этим чипом на стартовой станции + на станциях отметки, и проверяю ее наличие в SportIduinoPQ. Но кроме записи 255 и не верного времени ничего не показывается. В чем может быть моя ошибка при настройке станций? В SportOrg также ошибка старта.

**Comment by mars2860** [comment]
Если вы собрали базовою станцию по последней схеме из репозитория, то это новая схема и для неё ещё нет прошивки под чипы ntag, только mifare

По этой схеме собирали станцию?
https://github.com/alexandervolikov/sportiduino/blob/master/Base%20station/hardware/prod/sportiduino-base-scheme.jpg

**Comment by SergeyZaboev** [comment]
Да, по этой схеме. Но, после написания сообщения я перезалил прошивку для mifare и результат почти тот же, мастер-чипы с мастер станции записываются, а вот сами станции при его поднесении отвечают мгновенно длинным сигналом, затем при поднесении чипа участника раздается короткий сигнал, я там понимаю о том что запись отметки произведена, но при считывании в SportIduinoPQ чип остаётся пустым.

**Comment by mars2860** [comment]
Скорее всего не настроены часы в базовой станции/номер станции или не проинициализирован чип отметки. В новой версии SportduinoPQ можно создать мастер чип для чтения настроек базовой станции. Создайте этот чип и проверьте настройки базовой станции (часы, номер станции)

**Comment by SergeyZaboev** [comment]
Спасибо

**Comment by SergeyZaboev** [comment]
Прошил мастер-станцию и станции отметки прошивкой mifare из релиза 1.37, сделал мастер чип для коррекции времени, приложил его, затем для стартовой станции тоже самое. Сделал чип для чтения дампа. Приложил его к станции старта. Считал информацию с чипа в SportIduinoPQ 0.6.0. Получил
Read dump from cp: 13
Total punches: 10
14, 15, 16, 17, 18, 19, 20, 21, 22, 23.
 Ни времени, ни номера стартовой КП.

**Comment by alexandervolikov** [comment]
В дампе станции время отметок не хранится, только факт отметки. То есть приведенные данные говорят следующее: на станции под номером 13 отметились чипы с номерами 14, 15, 16, 17, 18, 19, 20, 21, 22, 23.
Время отметки хранится только на чипе.

**Comment by SergeyZaboev** [comment]
А я присваивал станции стартовый номер, то есть она должна быть 240. Для эксперимента я работал с одним чипом и стартовой станцией. Все делал после сразу прошивки. То есть не должно было быть на станции отметки этими чипами.

Я конечно извиняюсь за наглость в таких вопросах, но очень хочется воспроизвести работу станций.

**Comment by SergeyZaboev** [comment]
Видимо я не разобрался и заказал платы из релиза 1.42. А прошить не знаю точно какой версией прошивки. Вот и задаю вопросы.

**Comment by mars2860** [comment]
Покажите фото печатной платы, которую вы собрали и скрин программы SportiduinoPQ

**Comment by SergeyZaboev** [comment]
![IMG_20190425_204754](https://user-images.githubusercontent.com/2853816/56749824-e882f880-679b-11e9-9644-11abae186b5d.jpg)
![SportiduinoPQ](https://user-images.githubusercontent.com/2853816/56749831-ed47ac80-679b-11e9-865e-49f5a7ca9080.png)

**Comment by mars2860** [comment]
Вы собрали новую версию печатной платы. С этой платой работает новая версия [прошивки](https://github.com/alexandervolikov/sportiduino/blob/master/Base%20station/firmware/MifareBaseStation/MifareBaseStation.ino.standard.hex). Прошивать её нужно программатором. Никаких бутлоадеров до и после прошивать не надо. Поддерживаются только чипы Mifare. К сожалению, сейчас есть путаница с документацией и тем, что лежит в хеде репозитория. То что в хеде репозитория ещё не вошло в релиз и не документировано. Там есть новые функции и некоторые не соответствия с сигналами, которые подаёт станция по сравнению с текущей документацией. Но задавайте вопросы и я на них отвечу.

Судейскую станцию надо прошить этой [прошивкой](https://github.com/alexandervolikov/sportiduino/blob/master/Master%20station/firmware/usb/MifareMasterStation/MifareMasterStation.ino)

По сборке - светодиод в этой версии не надо так отгинать, устанавливайте его прямо. Черные BLS разъёмы на плату также не надо впаивать, иначе вы не сможете установить батарею.
Программу SportiduinoPQ возьмите отсюда https://github.com/mars2860/SportiduinoPQ. Чтобы прочитать настройки станции нужно создать GetInfo Card. 
![изображение](https://user-images.githubusercontent.com/8994211/56752083-ced7b600-6787-11e9-9150-76f69743debd.png)

**Comment by SergeyZaboev** [comment]
Спасибо, буду пробовать

**Comment by SergeyZaboev** [comment]
![SportiduinoPQ](https://user-images.githubusercontent.com/2853816/56758104-3b19e000-67af-11e9-8617-b098558fc95f.png)
Прошил две станции отметки и мастер-станцию, Сделал чип чтения настроек. Получил исходные данные настроек станций. Затем сделал чип установки времени. Приложил его к одной из станций. Станция издала чёткий сигнал (соответственно если задержать чип в поле антенны, то она выдаёт сигнал в соответствии с частотой поиска чипа - я так понимаю). Затем сделал чип чтения настроек снова и приложил его к станции а затем прочитал - ничего не изменилось. На изображении нет, но я тоже самое делал и со второй станцией - результат один.

А может я часы припаял неверно (выемка на микросхеме смотрит на МК)?

**Comment by SergeyZaboev** [comment]
Номера станциям также не присваиваются

**Comment by SergeyZaboev** [comment]
То есть со стороны SportiduinoPQ и мастер-станции всё работает, а на стороне станции отметки вижу только звуковые и световые сигналы. Даже в чип участника не пишет отметку

**Comment by mars2860** [comment]
После сборки у станций отметки пароль (0,0,0). Судя по скрину, вы установили пароль для мастер-чипов (255,255,255), поэтому станция отметки просто отвергает все ваши мастер-чипы. Установите в программе SportiduinoPQ пароль (0,0,0) и нажмите Apply. После этого создавайте мастер-чипы.

![изображение](https://user-images.githubusercontent.com/8994211/56759015-3564d000-6798-11e9-9fb8-1ffec1e17295.png)

**Comment by SergeyZaboev** [comment]
![SportiduinoPQ](https://user-images.githubusercontent.com/2853816/56759143-be3c3580-67b1-11e9-9423-d9429113d1c1.png)
Ещё тестировал - присвоил станции номер 31, читаю её настройки, в них она уже № 255 и время новое само появляется, на новые настройки станция также не откликается.

**Comment by SergeyZaboev** [comment]
Ок, увидел поздно сообщение. Пробую

**Comment by SergeyZaboev** [comment]
Заработало, только на одной станции время изменилось на точное, а на второй никак, но уже остальные настройки присваиваются.

Супер!

**Comment by SergeyZaboev** [comment]
Пропаял дополнительно ноги у часов и время встало на место.

**Comment by mforis** [comment]
Добрый день! Какая самая новая прошивка для этих базовых станций?

**Comment by mforis** [comment]
![image](https://user-images.githubusercontent.com/32615135/56783256-91107700-67f3-11e9-8187-e604aebc01f9.png)

**Comment by mars2860** [comment]
Для этой платы новой версии прошивки нет. Последняя для чипов Mifare [здесь](https://github.com/alexandervolikov/sportiduino/tree/master/Base%20station/firmware/MifareBaseStationOld)

**Comment by mforis** [comment]
Я и использую Mifare, но платы у меня старые, а хотелось бы использовать новые функции

**Comment by mars2860** [comment]
Только если на старой плате резать дорожки и делать проводками перемычки, чтобы на ней работала новая прошивка

**Comment by mforis** [comment]
Хорошо, а какие именно отличия в платах?

**Comment by mars2860** [comment]
Отличия:
1. Прерывание DS3231 (нога 3) подключено к порту PC3 (нога 26)
2. Порт PD2 (нога 32) подключена к пину RST DS3231 (нога 4)
3. Пин VCC DS3231 (нога 2) отключен от порта PD5 и подключен к цепи +3V3. На порт PD5 теперь подключен пин 32 kHZ DS3231 (нога 1) плюс подтягивающий резистор на 3,3 кОм
4. К порту PD6 (нога 10) подключено прерывание RC522 (6 нога модуля)
5. Вместо биполярного транзистора для управления буззером установлен полевой транзистор
6. Номиналы подтягивающих резисторов I2C уменьшены с 10 кОм до 3,3 кОм

Из всего этого в принципе достаточно на старой плате порезать дорожку от PD5 до DS3231 и кинуть перемыку от 3-го пина DS3231 к порту PC3 (пин 26). Остальные изменения в схеме пока не используются и оставлены для будущих идей. Можно ещё заказать новые печатные платы и перепаять детали. В Китае платы дешевые, мне 50 штук за 800р с копейками сделали
