### ISSUE TITLE
SportiduinoPQ

### ISSUE THREAD

**Issue by Turaev58** [alexandervolikov/sportiduino#58]
Здравствуйте!
Ноутбук 10", не помещается нижняя часть "Настройки#1" и "Настройки#2". Не могу настроить Мастер-чип "Сон" и настройка по UART. Возможно ли прикрутить ползунок сбоку для прокрутки?
Спасибо.

**Comment by mars2860** [comment]
Прикрутил

**Comment by Turaev58** [comment]
Спасибо!
