### ISSUE TITLE
Разъём программирования с защитой от неправильного включения

### ISSUE THREAD

**Issue by sembruk** [alexandervolikov/sportiduino#68]
Предлагаю в новой версии платы использовать разъём типа [IDC-10MS](https://www.chipdip.ru/product/idc-10ms) (вилка на плату). Ответная часть на шлейф — [IDC-10F](https://www.chipdip.ru/product/idc-10f) монтируется без пайки.
Он имеет шаг 2,54 мм. Поэтому, если нет таких под рукой, на плату можно запаивать разъёмы старого типа.

**Comment by mars2860** [comment]
Да, идея правильная. Сам об этом думал, чтобы разъём под программирование был с ключом. Хотел найти, что-нибудь поменьше IDC-10 и такое же доступное, но не нашёл. Если ставить IDC-10, то получается всё очень плотно. Расстояние между стойками корпуса по ширине 33.5мм минус 12мм бузер, остаётся 21.5 мм. Сам IDC-10 = 20.5мм. В принципе влезет, если ставить всё с одной стороны.

**Comment by sembruk** [comment]
А если развернуть разъём вдоль и расположить над RFID модулем? Ножки разъёма не должны в него упираться.

**Comment by sembruk** [comment]
Также предлагаю расположить RX и TX на разъёме рядом.

**Comment by halny123** [comment]
Если хотите разъем, то только с верху или низу платы, иначе будут проблемы поместить бокс с батарейками. Он просто не влезет.
Наша первая версия плат разъем слева (правда не выводил под программатор пины мне показалось они лишние). И предложение все таки избавиться от светодиода выводного. Очень не технологично и не ремонтопригодно.

![image](https://user-images.githubusercontent.com/30285816/70554595-13348c80-1b86-11ea-8d8a-0314e680e6d5.png)
