### ISSUE TITLE
Версия платы с внешней памятью

### ISSUE THREAD

**Issue by sembruk** [alexandervolikov/sportiduino#69]
Планирую в ближайшее время развести плату v3 с посадочным местом под чип 24LC256.
Ветка ext-eeprom.

**Comment by mars2860** [comment]
Насколько понимаю внешняя EEPROM будет использоваться под журнал отметок или есть ещё какие идеи?

**Comment by sembruk** [comment]
Да, для этого.

**Comment by sembruk** [comment]
Добавил память в схему и переделал подключение разъёма программирования
![](/sportiduino/sportiduino/blob/ext-eeprom/hardware/BaseStation/prod/v3/sportduino-base-v3m-scheme.png?raw=true)

**Comment by mars2860** [comment]
Вроде всё норм. Версию можно просто 3 без m, всё равно прошлая схема ещё не вошла в релиз. Тогда эту схему добавим в новый релиз и она будет 3-й версией. И может ещё стоит подумать и как-то привести к общему знаменателю идею Виталия (@halny123) с радиомодулем и текущую схему и создать один официальный релиз. Возможно, вместо NRF радиомодуля использовать bluetooth модуль HC-08. Золотой Маршрут выбрал в качестве отметки систему "Фрактал", там вроде bluetooth. На будущее возможно можно будет сделать совместимость с этой системой. Кто что думает?

**Comment by sembruk** [comment]
В Телеграм-чате Максим предложил хорошую идею: пробуждать станцию по геркону. Можно пробуждать по геркону и чипу.
При этом не нужно каждые 25 секунд включать RFID модуль и в режиме сна можно существенно понизить потребление.

**Comment by sembruk** [comment]
Я считаю, что совместимость с Фракталом не нужна. По крайней мере пока.

**Comment by mars2860** [comment]
Можно сделать так. В схему добавить геркон как у Виталия. На разъёме программирования X2 выкинуть VBAT и вместо него подключить какой-либо порт МК, например, PB0 или PD7 - это будет Chip Select для другого устройства SPI. По желанию, пользователь пусть хочет ставит NRF или Bluetooth или вообще ничего. Радиомодуль будет ставиться дополнительно с торца корпуса и подключаться к разъёму программирования, ведь этот разъём всё равно пустует, когда корпус закрыт. Надо тебе обновить прошивку - открутил крышку, вытащил радиомодуль из разъёма программирования, перепрошил, поставил радиомодуль обратно. Или даже для пользователей с радиомодулем бутлоадер сделать для бесконтактного обновления прошивки. Идей много. И сейчас для этого в принципе надо только геркон добавить и вместо VBAT какой-нибудь порт.

**Comment by mforis** [comment]
Семён прав, ни вижу особого смысла использовать радиомодули, так как возастет потребление. Да и вообще не вижу смысла склеивать две системы. А вот геркон вещь хорошая. А по поводу NRF его можно использовать для реализации бесконтактной отметки, то есть сделать активный чип, как вариант, хотя это достаточно дорого + увеличивает потребление

**Comment by halny123** [comment]
Ребята может в чат перелезем по обсуждению ? Я могу рассказать что есть у меня сейчас чем доволен чем нет . А сюда уже выложить выжимки из обсуждений. А то в проблемах будет много мусора.
Кратко:
- Герконом доволен полностью не жалею что сделал. Просыпаюсь мгновенно. Если нужно можно сделать засыпание.
- Радиомодуль - как таковой оказался не востребован, побаловался и все. для настройки все же быстрее чипами оказалось. Была задумка использовать для перепрошивки, optiboot позволяет OTA прошивку делать. Но это настолько редко, что легче открутить крышку и нормально перешить. Поэтому отказался от него.
- Внешняя память - не увидел необходимости вообще. Критично только наличие номера чипа - время не критично. Если уж нужно примерно знать время отметки - можно вычислить по соседним чипам. (Отказался)
- Сейчас задумка отказаться от чипов для программирования за счет использования на мастер станции модуля PN532 - который должен поддерживать режим эмуляции чипа. Но пока детали в пути сказать работает или нет задумка не могу. Тогда необходимость в радиомодуле отпадет вообще.
Это все только мое мнение у других требования к отметке могут быть иные.

**Comment by halny123** [comment]
> Можно сделать так. В схему добавить геркон как у Виталия. На разъёме программирования X2 выкинуть VBAT 

Я бы предложил выбросить Vcc а питание заводить все таки на VBAT.
Не дай бог кто то воткнет что то больше 3.3В. Пусть лучше сгорит стабилизатор чем что то еще.
А при программировании готовых станций питание все равно от батареек берем.

**Comment by sembruk** [comment]
Ещё хочу убрать фильтр с линии Reset Атмеги. Так как сигнал с DTR идёт через конденсатор, то имульс получается очень коротким. Будет ли с фильтром работать обновление прошивки?

**Comment by mars2860** [comment]
> 
> 
> Ещё хочу убрать фильтр с линии Reset Атмеги. Так как сигнал с DTR идёт через конденсатор, то имульс получается очень коротким. Будет ли с фильтром работать обновление прошивки?

Ещё не проверял как эта цепь будет работать, но всё же выбрасывать думаю не стоит. Если это будет мешать программированию, то можно просто не распаивать этот фильтр.

**Comment by sembruk** [comment]
![](/sportiduino/sportiduino/blob/ext-eeprom/hardware/BaseStation/prod/v3m/sportiduino-base-v3m-scheme.png?raw=true)

**Comment by mars2860** [comment]
PC3 зарезервирована под управление питанием DS3231. Здесь я уже сделал ошибку, когда VCC была жестко к 3v3. Сейчас мы хотим попробовать VCC=0, R1,R3 = 3V3, но неизвестно пока какое будет потребление, поэтому мной были добавлены печатные джамперы, которые позволяют вернуться к проверенному решению из версии 1. Лучше PB6 или PB7 задействовать. Кварцы ставить точно не будем.

**Comment by sembruk** [comment]
> Ещё не проверял как эта цепь будет работать, но всё же выбрасывать думаю не стоит. Если это будет мешать программированию, то можно просто не распаивать этот фильтр.

Да, с RC фильтром на RST не обновляется прошивка. Думаю, всё-таки его убрать с платы. А для предотвращения перезагрузки станции при поключении USB-UART можно физически отключать DTR.
