### ISSUE TITLE
For NTag cards master station return card type code 0x06 (Mifare Ultralight)

### ISSUE THREAD

**Issue by sembruk** [alexandervolikov/sportiduino#73]
Master station firmware v1.6.1

**Comment by sembruk** [comment]
Tested with NTag215 and NTag216.

**Comment by mars2860** [comment]
Скорее всего проблема в ntagCardPageRead. При вызове этой функции, наверное, надо передавать буфер размером 18 байт, а сейчас для чипов NTAG передаётся буфер 4 байта.

**Comment by sembruk** [comment]
Спасибо! Да дело в этом. Вчера нашёл проблему, но не залил.
