### ISSUE TITLE
Пробуждать станцию с помощью магнита

### ISSUE THREAD

**Issue by sembruk** [alexandervolikov/sportiduino#75]
или магнита и чипа.
На плате v3 для этого предусмотрен геркон.

**Comment by halny123** [comment]
Осмелюсь предложить следующий алгоритм, который позволит и пробуждать и усыплять станцию магнитом.
При однократном касании магнитом - станция пробуждается (через перегрузку). 
Если магнит удерживать - после перегрузки в setup - проверять состояние геркона - если он будет оставаться замкнут - усыплять станцию.

**Comment by sembruk** [comment]
Усыпление станции магнитом опасно: могут намеренно или случайно усыпыть её в лесу.

**Comment by sembruk** [comment]
0361a05
Теперь по умолчанию станция опрашивает чип каждые 25 сек (как и раньше). Если сработал геркон, чип опрашивается немедленно.
Если определить NO_POLL_CARDS_IN_SLEEP_MODE в прошивке, станция не будет опрашивать чип, пока не сработает геркон.
