### ISSUE TITLE
Пищалку почти не слышно

### ISSUE THREAD

**Issue by sembruk** [alexandervolikov/sportiduino#8]
Поэтому приходится смотреть на световую индикацию, а не в карту.

**Comment by mforis** [comment]
Вполне возможно, что у вас проблема в зуммерах, есть вариант вместо резистора перед зуммером использовать перемычку.

**Comment by alexandervolikov** [comment]
Да, согласен, проблема пищалок есть. Видимо, сказывается то, что приобретал их я задешево и ставил особо не отбирая, поэтому они различаются по громкости и тональности. 
В будущем, да, поищу изначально более качественные.

**Comment by alexandervolikov** [comment]
Протестировал разные варианты и решил ставить пищалку Jl WorldHC0903A. Не сильно громкая, но достаточно надежная и дешевая.
