### ISSUE TITLE
Проверить поведение станции при севших батареях

### ISSUE THREAD

**Issue by Pavel-Y** [alexandervolikov/sportiduino#82]
В прош. 1.3.х (0х67) станция стала пищать раз в ~5 секунд, не переставая. Есть предположение, что это из-за севших батарей. 
Можно реализовать другое поведение?

**Comment by sembruk** [comment]
Новые прошивки так себя не ведут.

**Comment by sembruk** [comment]
При севших батареях станция просто не подаёт признаков жизни.
