### ISSUE TITLE
Заливка прошивки в Atmega.

### ISSUE THREAD

**Issue by mforis** [alexandervolikov/sportiduino#9]

**Comment by mforis** [comment]
Можно ли залить прошивку через Arduino Uno без программатора?

**Comment by alexandervolikov** [comment]
Наверное, как-то это можно осуществить, если сделать прошивку совмещенную с буатлоадером, который умеет обрабатывать корректно прерывания от watchdog. Если заливать как есть просто через ArduinoAsISP, то она не работает, уходит в bootloop.

**Comment by mforis** [comment]
Блииииннн... Очень плохо... Необходимо где-то срочно искать программатор...

**Comment by mforis** [comment]
А что у вас за программатор?

**Comment by alexandervolikov** [comment]
Я пользуюсь самым дешевым USB TTL-UART на чипе CHG340
https://ru.aliexpress.com/store/product/CH340G-5V-USB-to-TTL-UART-Serial-Converter/1950989_32524218818.html

Сейчас глянул, да можно обойтись и Arduino UNO для заливки прошивки, но из UNO нужно вытащить чип Atmega, если это возможно, или замкнуть Reset на землю (https://forum.arduino.cc/index.php?topic=146258.0)
Тогда Arduino UNO превраиться в USB to UART и можно залить прошивку.

Но перед этим всё-равно надо залить правильный буатлодер - Optiboot
(https://github.com/Optiboot/optiboot)
пользуясь ArduinoAsISP на UNO.

**Comment by mforis** [comment]
Александр, еще вопрос, а если у меня копия Arduino Uno с чипом CH340G? Могу ли я сразу прошить или так-же необходимо выполнять указания выше? Спасибо и извините за назойливость)))

**Comment by alexandervolikov** [comment]
Сначала  залить прошивку ArduinoAsISP на Arduino UNO
(File - Examlpes - ArduinoAsISP). На Arduino UNO разместить конденсатор 10 мкФ между RST и GND. Подключить к программируемой плате пины 11,12,13 к MOSI, MISO, SCK соответственно. Пин 10 подключить к RST программируемой платы и запитать плату.

Далее установить Optiboot в IDE:
вставить URL-адресс:
https://github.com/Optiboot/optiboot/releases/download/v6.2/package_optiboot_optiboot-additional_index.json
в  "Additional Boards Manager URLs" в File-Prefernces
После этого прошивки станут ддоступны через меню Tools-Board
Для прошивки  нужно выбрать:
Board: Optiboot on 32 pins
Processor: ATmega328p
CPU Speed: 8Mhz (int)
Programmer: Arduino As ISP

Нажать Burn bootloader
Если всё нормально, появиться надпись 
Done burning boatloader 
Если нет, то где допущена ошибка, проверить правильность подключения, пайки и т.п.

Дальше отключаем UNO от программируемой платы. В IDE меняем программатор на "AVRISP mkII". Замыкаем на UNO пины  RST и GND. Подключаемм UNO к программируемой плате: RX-TX, TX-RX. Вроде как, если использовать UNO в качестве USB-UART, то пин RST на программируемой плате придётся нажимать (заземление для перезагрузки платы) вручную. Говорят, это нужно сделать в нужный момент во время загрузки прошивки, который определяется опытным путем.
С отдельным USB-UART, в котором есть DTR проще. Стоит он недорого, в том числе и в России.

**Comment by alexandervolikov** [comment]
Но, если хочется залить прошивку просто для теста. То можно из Stantion.ino удалить строчки:
sleep(work);
//Power down regime: sleep 24 s
  if (deepsleep) {
    for (uint8_t i = 0; i<3; i++){
      sleep8s();
    }
  }
Это отключит вход в энергосберегающие режимы, будет кушать значительно больше батарейку, но проверить функциональность можно. И залить через ArduinoAsISP.

**Comment by mforis** [comment]
Спасибо ОГРОМНОЕ! Если не сложно закиньте эту инструкцию в Wiki.

**Comment by mforis** [comment]
Нашел у себя Arduino Nano с чипом CH340G, как с помощью неё прошить Atmega? По той же инструкции или как-то по другому?   И будет ли работать прошивка версии 0.42 в плате версии 0.41(то есть без внешней памяти)?

**Comment by alexandervolikov** [comment]
Да, с Arduino Nano всё тоже самое. Только нужно ещё нужно установить драйвера на Windows для схемы CHG340, чтобы Windows видела эти устройства.
Да, с платой версии 0.41 всё будет работать. Сейчас и в прошивке по-умолчанию внешняя eeprom выключена, за включение/выключение отвечает строчка:
const boolean extEeprom = false;

**Comment by mforis** [comment]
Александр, пришли мне Atmegи и я впаял, начал заливать бутлоадер, но он не прошивается с такой ошибкой. Как решить проблему???
![image](https://user-images.githubusercontent.com/32615135/32990753-ee636408-cd3f-11e7-8d93-023542767dbc.png)

**Comment by alexandervolikov** [comment]
Вероятно, схема плохо пропаялась. Проверьте с лупой или тестером все контакты.

**Comment by mforis** [comment]
Блин, я всё уже по пять раз проверил, даже вторую плату собрал, но такая-же фигня...

**Comment by alexandervolikov** [comment]
А конденсатор 10 мкФ на uno между rst и gnd стоит?

**Comment by mforis** [comment]
Да, сейчас взял Нано, и выбило другую ошибку...
![image](https://user-images.githubusercontent.com/32615135/32991618-cbc208ea-cd4f-11e7-8184-f870a275d134.png)

**Comment by alexandervolikov** [comment]
У меня такая ошибка, обычно, выходит когда я плохо припаял. Казалось бы, всё делал четко и последовательно, все контакты пропаяны, но ошибка. Тогда ещё раз проходился паяльников по контактам и оно начинало работать. Худший вариант что может быть не так: атмега сгорела, например, если передержать паяльник на контактах.

Можете сделать следующее: снять с uno (или nano) конденсатор. Загрузить вот эту прошивку:
https://yadi.sk/d/aYVpiodu3PqAwH
И открыть Serial-port в IDE Arduino при подключенной программируемой плате. Это прошивка проводит диагностику и должна выдать то, что видит на SPI контактах.

**Comment by mforis** [comment]
![image](https://user-images.githubusercontent.com/32615135/32993258-6f6d62d0-cd66-11e7-89e4-f8f05cf9e249.png)

**Comment by mforis** [comment]
![image](https://user-images.githubusercontent.com/32615135/32993269-a77b13ac-cd66-11e7-87df-5326b7538b00.png)

**Comment by mforis** [comment]
Капец как я расстроился, нифига не получается, ничего не работает! И не могу понять в чем косяк.
Пайку проверил, пропоял еще раз и ничего...

**Comment by alexandervolikov** [comment]
Да, соединения с микроконтроллером нет. А как Вы соединялись платы? Можете прислать фото?
Не расстраивайтесь, я тоже бывало по нескольку часов сидел над платами в поисках ошибки

**Comment by mforis** [comment]
Да, сейчас скину фотки....

**Comment by mforis** [comment]
![7vu63gmk07y](https://user-images.githubusercontent.com/32615135/32993556-0f472c92-cd6b-11e7-958f-a5bdd66cdeda.jpg)
![eneypthx3qm](https://user-images.githubusercontent.com/32615135/32993553-073b4b6e-cd6b-11e7-8748-ecbebff50471.jpg)
![muge7f8u5lm](https://user-images.githubusercontent.com/32615135/32993554-07647b2e-cd6b-11e7-95bd-3e56f8189de1.jpg)

**Comment by mforis** [comment]
![7qnbdsntlxe](https://user-images.githubusercontent.com/32615135/32993590-6f5e1014-cd6b-11e7-9411-f5c1ed2fda82.jpg)
![x9sglfncjgi](https://user-images.githubusercontent.com/32615135/32993591-6f89a95e-cd6b-11e7-9b5e-2a4c24888873.jpg)

**Comment by alexandervolikov** [comment]
У Вас rst контроллера не подключен, это тот который уходит в другой конец платы (там где два ряда по три дырки, сейчас он у Вас не распаян). Тот rst, который подключен к Вас относится к rc522 и при прошивке он не задействован. 
Если не получится, еще можно попробовать прошить при 5в (переставить в uno соответствующий штырек )

**Comment by alexandervolikov** [comment]
Вот сравните с моими фото при прошивке
https://user-images.githubusercontent.com/32615135/32993556-0f472c92-cd6b-11e7-958f-a5bdd66cdeda.jpg
https://raw.githubusercontent.com/alexandervolikov/sportiduino/master/Images/s11.jpg

**Comment by mforis** [comment]
Всё бут прошил!
![image](https://user-images.githubusercontent.com/32615135/32993888-fc9b57a8-cd6f-11e7-8697-c0af9255ff09.png)

**Comment by mforis** [comment]
Теперь проблема с заливкой скетча, когда нажимать ресет и где? На ардруине?
![bbczjigqkv8](https://user-images.githubusercontent.com/32615135/32994248-80949d58-cd75-11e7-983d-0443fe2772df.jpg)
![pngjyc-sndw](https://user-images.githubusercontent.com/32615135/32994249-80de6438-cd75-11e7-8abf-bfb4d0c6385c.jpg)
![image](https://user-images.githubusercontent.com/32615135/32994250-8482e0be-cd75-11e7-9a0d-5df8c9f462f6.png)

**Comment by alexandervolikov** [comment]
Нет, нажимать нужно на програмируемой плате. Для этого в нужный момент нужно заземлить и отпустить контакт rst (тот же который в двух рядах по три дырки). Сам таким путем никогда не прошивал, поэтому тонкостей не знаю, но читал, что момент нажатия подбирается опытным путем, нужно некоторое число попыток.

**Comment by alexandervolikov** [comment]
Момент засеките по прогрессу загрузке в окне ардуино внизу справа, должно быть около 80% заполнения этой полосы. Когда скетч уже откомпилируется

**Comment by mforis** [comment]
Хорошо, спасибо. Завтра буду продолжать программирование плат.

**Comment by mforis** [comment]
После нажатия заземление RST процесс зависает....
![image](https://user-images.githubusercontent.com/32615135/33018610-246f2a50-ce08-11e7-8385-a1475c198d2a.png)

**Comment by mforis** [comment]
![image](https://user-images.githubusercontent.com/32615135/33018912-46bc0ab4-ce09-11e7-96e6-5d6eec527300.png)

**Comment by alexandervolikov** [comment]
Попробуйте сделать вот по этой инструкции:
https://www.youtube.com/watch?v=jk-uq3dlvKs
Только выбрав нужную прошивку и программатор.

**Comment by alexandervolikov** [comment]
То есть, задача такая же как прошить Arduino Pro Mini. В сети есть инструкции.

**Comment by mforis** [comment]
Пока залить скетч не получается....😢

**Comment by alexandervolikov** [comment]
Есть так же вероятность, что Rx Tx плохо пропаяны. Ещё также важно подключение попарно Rx-Tx, Tx-Rx. Возможно стоит питание подвести от 5 вольт при прошивке (у меня где-то платы 3 из 50 прошиваются только таким образом)

Но, возможно, что просто не удается поймать момент.
Тогда два пути. Заказать вот такую штуку:
https://ru.aliexpress.com/store/product/CH340G-5V-USB-to-TTL-UART-Serial-Converter/1950989_32524218818.html
Можно и из России, стоят они не дорого и там есть контакт Dtr, который собственно нажимает кнопку reset в нужный момент. (в данном экземпляре неправильная маркировка и соединять нужно Rx-Rx, Tx-Tx).

Ещё можно пожертвовать какой-нибудь ардуиной с сериал-портом (нано или уно), выпаять от туда Atmegу и использовать как в видео, которое я прилагал выше.

**Comment by alexandervolikov** [comment]
Да, кстати, сейчас посмотрел фотографии, что Вы присылали выше. На тех фотографиях у Вас подключен неправильный Reset. Выше я уже писал, что при прошивке микроконтроллера нужно использовать контакт, который находится в разъемах два ряда по три дырки. Reset, который находится ближе к микроконтроллеру относится к плате RC522.

**Comment by mforis** [comment]
А может проблема этом?
![image](https://user-images.githubusercontent.com/32615135/33027667-cfe09bd2-ce24-11e7-8f23-0a10a6fa2a55.png)

**Comment by alexandervolikov** [comment]
Не думаю. У меня при прошивке буатлоадера пишет тоже самое.

**Comment by mforis** [comment]
Ясно. Буду капать дальше...

**Comment by mforis** [comment]
А в плате RX слева и TX справа? А то шелкография не очень понятна...

**Comment by alexandervolikov** [comment]
Rx - ближний к микросхеме контакт, Tx - дальний

**Comment by mforis** [comment]
Самое интересное, что бут шьётся без "Б", а скетчи не хотят...

**Comment by mforis** [comment]
Уже и МК выпаивал... И чего только не делал...

**Comment by alexandervolikov** [comment]
А пришлите фото как Вы с выпаянной МК подключаете платы между собой

**Comment by mforis** [comment]
Заработало!!!!!!!!!!!!!!!!!!!

**Comment by mforis** [comment]
Прошивал по этой инструкции, только с конденсатором. 
https://youtu.be/Rz1tFghOoiQ

**Comment by alexandervolikov** [comment]
Поздравляю! :-)

**Comment by mforis** [comment]
И опять новая проблема.... База запускается пикает три раза, через какое-то время пикает еще раз... И  всё больше от неё нет реакции...

**Comment by alexandervolikov** [comment]
Предварительно стоит записать мастер-чипы номера станции (240 например), обновления времени и пару обычных чипов. После вставления батареек станция три раза пикнет, что говорит и том, что часы выставлены не верно. Затем через 5 секунд будет длинный сигнал, сигнализирующий, что программа вошла в цикл работы. По умолчанию это режим сна, поэтому станция среагирует на чип устаноки номера станции только через 25 секунд после её поднесения, но можно сразу положить станцию на чип перед вставкой батарей. Станция запишет новый номер ,перезагрузится, и теперь уже способна реагировать на обычные чипы. Подносим чип, ждем до 25 секунд, станция переходит в рабочий режим. Но часы по-прежнему сбиты. В рабочем цикле подносим мастер-чип времени и после перезагрузки подносим второй обычный чип. Считываем его на станции сопряжения и убеждаемся в корректной работе. Если всё так, то станцию можно отмывать. Если нет, то нужно поискать возможные ошибки, прежде всего, в спайке модуля RFID.

**Comment by alexandervolikov** [comment]
Принципиальную работу модуля ещё можно проверить, если залить туда прошивку из примера DumpInfo библиотеки RC522:
https://github.com/alexandervolikov/sportiduino/blob/master/Libraries/RFID/examples/DumpInfo/DumpInfo.ino

**Comment by mforis** [comment]
При подносе мастер чипа база 6 раз пикает, потом пикает  быстро 3 раза и начинает бысро пикать в чем проблема?

**Comment by alexandervolikov** [comment]
Возможно, бутлоадер не тот. Вы заливали при прошивке optibut 32pin 8mhz?

**Comment by mforis** [comment]
![image](https://user-images.githubusercontent.com/32615135/33076418-bbc1c55e-cedd-11e7-96f9-85656aeb17a6.png)

**Comment by mforis** [comment]
А кстати, вы есть в ВК? Может там будет удобнее общаться?

**Comment by alexandervolikov** [comment]
Да, вроде всё верно. Просто признаки - беспрерывное пикание может указывать на то, что вотчдог работает некорректно. Не знаю в чём проблема. А можете скинуть фото спаянной схемы?
В вк я есть, но там общаться не очень удобно. Лучше здесь или по почте:
ab.volikov@gmail.com

**Comment by mforis** [comment]
А может это следствие моего метода прошивки?

**Comment by alexandervolikov** [comment]
Не, не думаю.
А какую версию прошивки Вы загружали?

**Comment by mforis** [comment]
0.43

**Comment by mforis** [comment]
![image](https://user-images.githubusercontent.com/32615135/33086235-146efd88-cef8-11e7-9fdc-00c6bffb9338.png)

**Comment by alexandervolikov** [comment]
Посмотрел видео по методу заливки прошивки. Да, дело в этом. Таким образом вместе с заливкой прошивки стирается буатлоадер. Поэтому функции связанные с вотчдогом перестают нормально работать.
Так что, предлагаю просто купить и подождать Serial-TTL конвертер. Только нужно обязательно с работающим DTR пином брать. По ссылке выше от Robotdyn работающий.

Если хочется протестировать как всё работает, то можно залить прошивку методом, который у Вас получился. Только в цикле loop оставить лишь одну функцию - rfid():

void loop ()
{
 rfid();
}

Все функции, связанные с вотчдогом в таком случае будут отключены. Всё даже быстрее будет работать, но и энергопотребления будет большим. Комплекта пальчиковых батареек хватит лишь примерно на 5 дней.

**Comment by mforis** [comment]
![img_20171201_165552](https://user-images.githubusercontent.com/32615135/33486723-335ab3f6-d6bc-11e7-8aef-e454f50da7f4.jpg)
Раздобыл такой конвертер, сегодня буду пробовать опять прошить.
![img_20171201_165544](https://user-images.githubusercontent.com/32615135/33486715-29b0f9c8-d6bc-11e7-8796-617c126f4307.jpg)

**Comment by mforis** [comment]
Одну базу собрал полностью, ещё 4 прошил, осталось ещё 5))) И буду проводить испытания, а там если всё ок буду заказывать новую партию деталей.
![gif_1512157823039](https://user-images.githubusercontent.com/32615135/33500555-403fca38-d6ea-11e7-83c3-30b912a292d1.gif)
