### ISSUE TITLE
Разница между кодом SportIduinoPQ, firmware и протоколом в GitHub'e

### ISSUE THREAD

**Issue by sportiduino-lite** [alexandervolikov/sportiduino#98]
Код SportIduinoPQ сейчас реализует не протокол, выложенный в этом же репозитории - https://github.com/sportiduino/sportiduino/blob/master/Doc/ru/Card.md , а какой-то другой. Он не описан в явном виде, только в коде SportIduinoPQ.

Тем, кто пишет код не для SportIduinoPQ, а для других программ, нужен чётко описанный логичный протокол.

**Comment by sportiduino-lite** [comment]
В частности, но не только:

Запись 0 для MifareClassic1k чипа участника в байт [2], где для NTag 0 означает, что чип очищен, а для участников там 3, 5 или 6 (кодируют ёмкость чипа), создает **неконсистентный** протокол. 
Нужно исправить для MifareClassic1k на ненулевое фиксированное значение, например на 8 (используется в другой программе).

Вот сюда
https://github.com/sportiduino/sportiduino/blob/master/firmware/MasterStation/MasterStation.ino#L273

Добавить 
```
case CardType::MIFARE_1K: 
            ntagType = 8;
            break;
```

**Comment by sembruk** [comment]
Значение 0 записывается не только для MifareClassic1k, но и для всех неNTag чипов.
Этот байт используется только в прошивках старее версии 6. Он оставлен для совместимости, и может быть убран в любой момент (кроме значения 255 для мастер-чипа). Использовать его значение о типе чипа и тем более как индикатор очистки чипа в новом софте нельзя!

**Comment by sembruk** [comment]
> Код SportIduinoPQ сейчас реализует не протокол, выложенный в этом же репозитории - https://github.com/sportiduino/sportiduino/blob/master/Doc/ru/Card.md , а какой-то другой. Он не описан в явном виде, только в коде SportIduinoPQ.

С одним частным случаем разобрались. Теперь прошу указать на другие несоответсвия описания протокола, и реального поведения.
